#!/usr/bin/env python
"""
Generate the standalone `run_*.py` example scripts in this directory from
`../Notebooks/workshop_lib.py`.

Why generate rather than hand-write: each `run_*.py` is meant to be copied
by a student into their own work directory and run on its own, so it must
NOT `import workshop_lib`. But the notebook's analysis cells assume the
flows were built with *exactly* the same `AbinitInput`/`Flow` code as
`workshop_lib.py` -- so hand-duplicating that code into each script would
risk the two silently drifting apart. Instead, this script pulls the
relevant functions (structure loaders, input builders, `build_*_flow()`,
`setup_manager()`) straight out of `workshop_lib.py` with
`inspect.getsource()` and stitches each one into a self-contained script
with its own path setup and a `flowtk.flow_main()` entry point.

Whenever `workshop_lib.py` changes, re-run this from `Tutorial/Examples/`:

    python generate_examples.py
"""
import inspect
import sys
from pathlib import Path

EXAMPLES_DIR = Path(__file__).resolve().parent
NOTEBOOKS_DIR = EXAMPLES_DIR.parent / "Notebooks"
sys.path.insert(0, str(NOTEBOOKS_DIR))
import workshop_lib as wlib  # noqa: E402  (needs the sys.path tweak above)

GENERATED_NOTICE = (
    "# Auto-generated by generate_examples.py from workshop_lib.py.\n"
    "# Do not edit by hand: edit workshop_lib.py and re-run generate_examples.py.\n"
)

PATH_SETUP = """\
# This script is meant to be copied -- together with the rest of this
# Tutorial/ directory -- into your own work directory. Data/Pseudos and
# Data/Structures are located relative to *this file*, wherever that ends
# up. The flow itself is built in the *current* directory: wherever you run
# "python {fname}" from.
SCRIPT_DIR = Path(__file__).resolve().parent
DATA_DIR = SCRIPT_DIR.parent / "Data"
PSEUDO_DIR = DATA_DIR / "Pseudos"
STRUCTURE_DIR = DATA_DIR / "Structures"
"""


def src(name):
    """Exact source of a top-level function in workshop_lib.py, by name."""
    return inspect.getsource(getattr(wlib, name)).rstrip("\n") + "\n"


class Recipe:
    def __init__(self, fname, docstring, chunks, entry_fn, workdir,
                 extra_imports="", needs_gaas_cif=False, needs_si_cif=False,
                 needs_fcc_kpath=False):
        self.fname = fname
        self.docstring = docstring
        self.chunks = chunks
        self.entry_fn = entry_fn
        self.workdir = workdir
        self.extra_imports = extra_imports
        self.needs_gaas_cif = needs_gaas_cif
        self.needs_si_cif = needs_si_cif
        self.needs_fcc_kpath = needs_fcc_kpath


RECIPES = [
    Recipe(
        fname="run_gaas_gstate.py",
        docstring="""\
Companion to Section 3 ("Ground-state total energy of GaAs") of the
workshop notebook.

Builds the same flow as `workshop_lib.build_gs_flow()` and writes it to
disk, so it can be launched and monitored from a terminal on the cluster
instead of blocking the notebook kernel with `flow.make_scheduler().start()`.

Usage
-----
    python run_gaas_gstate.py             # build the flow, don't run it yet
    abirun.py flow_gaas_gstate scheduler  # ... then run it (repeat if interrupted)
    abirun.py flow_gaas_gstate status     # ... or just check progress

    python run_gaas_gstate.py -s          # build *and* run in a single step
    nohup python run_gaas_gstate.py -s > log 2> err &   # ... in the background
""",
        chunks=["gaas_structure", "gs_input", "setup_manager", "build_gs_flow"],
        entry_fn="build_gs_flow",
        workdir="flow_gaas_gstate",
        needs_gaas_cif=True,
    ),
    Recipe(
        fname="run_gaas_convecut.py",
        docstring="""\
Companion to Section 4.1 ("ecut convergence") of the workshop notebook.

Builds the same flow as `workshop_lib.build_ecut_conv_flow()`: one SCF task
per value of `ecut`. After it completes, the notebook's `GsrRobot` /
`ConvergenceAnalyzer` cells collect the results into a convergence plot.

Usage
-----
    python run_gaas_convecut.py
    abirun.py flow_gaas_convecut scheduler
    abirun.py flow_gaas_convecut status

    python run_gaas_convecut.py -s        # build *and* run in a single step
""",
        chunks=["gaas_structure", "gs_input", "setup_manager", "build_ecut_conv_flow"],
        entry_fn="build_ecut_conv_flow",
        workdir="flow_gaas_convecut",
        needs_gaas_cif=True,
    ),
    Recipe(
        fname="run_gaas_convkpt.py",
        docstring="""\
Companion to Section 4.2 ("k-point convergence") of the workshop notebook.

Builds the same flow as `workshop_lib.build_kpt_conv_flow()`: one SCF task
per automatically-generated k-mesh density. After it completes, the
notebook's `GsrRobot` cell collects the results and plots energy per atom
against k-point density.

Usage
-----
    python run_gaas_convkpt.py
    abirun.py flow_gaas_convkpt scheduler
    abirun.py flow_gaas_convkpt status

    python run_gaas_convkpt.py -s        # build *and* run in a single step
""",
        chunks=["gaas_structure", "gs_input", "setup_manager", "build_kpt_conv_flow"],
        entry_fn="build_kpt_conv_flow",
        workdir="flow_gaas_convkpt",
        needs_gaas_cif=True,
    ),
    Recipe(
        fname="run_gaas_ebands.py",
        docstring="""\
Companion to Section 5 ("Band structures: GaAs vs Si") of the workshop
notebook, GaAs half.

Builds the same flow as `workshop_lib.build_gaas_ebands_flow()`: a
ground-state run on a homogeneous k-mesh followed by a non-self-consistent
run along the L-Gamma-X path. See also `run_si_ebands.py` for the silicon
comparison.

Usage
-----
    python run_gaas_ebands.py
    abirun.py flow_gaas_ebands scheduler
    abirun.py flow_gaas_ebands status

    python run_gaas_ebands.py -s        # build *and* run in a single step
""",
        chunks=["gaas_structure", "_bandstructure_inputs", "setup_manager", "build_gaas_ebands_flow"],
        entry_fn="build_gaas_ebands_flow",
        workdir="flow_gaas_ebands",
        needs_gaas_cif=True,
        needs_fcc_kpath=True,
    ),
    Recipe(
        fname="run_si_ebands.py",
        docstring="""\
Companion to Section 5 ("Band structures: GaAs vs Si") of the workshop
notebook, Si half.

Builds the same flow as `workshop_lib.build_si_ebands_flow()`: a
ground-state run on a homogeneous k-mesh followed by a non-self-consistent
run along the L-Gamma-X path, this time for silicon. See also
`run_gaas_ebands.py` for the GaAs run this is compared against -- GaAs has a
direct gap at Gamma, while silicon's fundamental gap is indirect.

Usage
-----
    python run_si_ebands.py
    abirun.py flow_si_ebands scheduler
    abirun.py flow_si_ebands status

    python run_si_ebands.py -s        # build *and* run in a single step
""",
        chunks=["si_structure", "_bandstructure_inputs", "setup_manager", "build_si_ebands_flow"],
        entry_fn="build_si_ebands_flow",
        workdir="flow_si_ebands",
        needs_si_cif=True,
        needs_fcc_kpath=True,
    ),
    Recipe(
        fname="run_gaas_eos.py",
        docstring="""\
Companion to Section 6 ("Equation of state and the lattice parameter") of
the workshop notebook.

Builds the same flow as `workshop_lib.build_eos_flow()`: one SCF task per
isotropically-scaled volume of GaAs around its experimental volume. After it
completes, the notebook fits the energy-volume curve with a Birch-Murnaghan
equation of state (`abilab.EOS`) to get the equilibrium volume and bulk
modulus. As noted in the notebook, this flow deliberately uses a coarse
`ecut`/k-mesh to stay cheap -- treat the numbers as illustrative, not
converged.

Usage
-----
    python run_gaas_eos.py
    abirun.py flow_gaas_eos scheduler
    abirun.py flow_gaas_eos status

    python run_gaas_eos.py -s        # build *and* run in a single step
""",
        chunks=["gaas_structure", "setup_manager", "build_eos_flow"],
        entry_fn="build_eos_flow",
        workdir="flow_gaas_eos",
        extra_imports="import numpy as np\n",
        needs_gaas_cif=True,
    ),
    Recipe(
        fname="run_gaas_phonons.py",
        docstring="""\
Companion to Section 7 ("Phonons from DFPT") of the workshop notebook.

Builds the same flow as `workshop_lib.build_phonon_flow()`: a ground-state
task producing the WFK file, followed by the symmetry-irreducible DFPT
atomic-perturbation tasks needed to assemble the dynamical matrix (and Born
effective charges) on a coarse q-mesh. This has more tasks than the other
example flows, so it is the best candidate for running in the background
with `nohup` (see below) rather than waiting on it in a foreground shell.

Usage
-----
    python run_gaas_phonons.py
    abirun.py flow_gaas_phonons scheduler   # repeat if interrupted
    abirun.py flow_gaas_phonons status       # check progress / list tasks

    python run_gaas_phonons.py -s                       # build *and* run
    nohup python run_gaas_phonons.py -s > log 2> err &   # ... in the background
""",
        chunks=["gaas_structure", "setup_manager", "build_phonon_flow"],
        entry_fn="build_phonon_flow",
        workdir="flow_gaas_phonons",
        needs_gaas_cif=True,
    ),
]


def render(recipe):
    parts = [f'#!/usr/bin/env python\n"""\n{recipe.docstring}"""\n', GENERATED_NOTICE]

    imports = "import sys\nfrom pathlib import Path\n\n"
    imports += recipe.extra_imports
    imports += (
        "import abipy.abilab as abilab\n"
        "import abipy.flowtk as flowtk\n"
        "from abipy.abilab import Structure\n"
    )
    parts.append(imports)

    constants = PATH_SETUP.format(fname=recipe.fname)
    if recipe.needs_gaas_cif:
        constants += f"GAAS_CIF = STRUCTURE_DIR / {wlib.GAAS_CIF.name!r}\n"
    if recipe.needs_si_cif:
        constants += f"SI_CIF = STRUCTURE_DIR / {wlib.SI_CIF.name!r}\n"
    if recipe.needs_fcc_kpath:
        constants += f"FCC_KPATH = {wlib.FCC_KPATH!r}\n"
    parts.append(constants)

    for chunk in recipe.chunks:
        parts.append(src(chunk))

    parts.append(f'DEFAULT_WORKDIR = {recipe.workdir!r}\n')

    footer = f"""\
def build_flow(options):
    flow = {recipe.entry_fn}(workdir=options.workdir or DEFAULT_WORKDIR)
    return setup_manager(flow)


@flowtk.flow_main
def main(options):
    return build_flow(options)


if __name__ == "__main__":
    sys.exit(main())
"""
    parts.append(footer)

    return "\n\n".join(p.rstrip("\n") for p in parts) + "\n"


def main():
    for recipe in RECIPES:
        out_path = EXAMPLES_DIR / recipe.fname
        out_path.write_text(render(recipe))
        print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
