#!/usr/bin/env python
"""
Companion to Section 4.2 ("k-point convergence") of the workshop notebook.

Builds the same flow as `workshop_lib.build_kpt_conv_flow()`: one SCF task
per automatically-generated k-mesh density. After it completes, the
notebook's `GsrRobot` cell collects the results and plots energy per atom
against k-point density.

Usage
-----
    python run_gaas_convkpt.py
    abirun.py flow_gaas_convkpt scheduler
    abirun.py flow_gaas_convkpt status

    python run_gaas_convkpt.py -s        # build *and* run in a single step
"""

# Auto-generated by generate_examples.py from workshop_lib.py.
# Do not edit by hand: edit workshop_lib.py and re-run generate_examples.py.

import sys
from pathlib import Path

import abipy.abilab as abilab
import abipy.flowtk as flowtk
from abipy.abilab import Structure

# This script is meant to be copied -- together with the rest of this
# Tutorial/ directory -- into your own work directory. Data/Pseudos and
# Data/Structures are located relative to *this file*, wherever that ends
# up. The flow itself is built in the *current* directory: wherever you run
# "python run_gaas_convkpt.py" from.
SCRIPT_DIR = Path(__file__).resolve().parent
DATA_DIR = SCRIPT_DIR.parent / "Data"
PSEUDO_DIR = DATA_DIR / "Pseudos"
STRUCTURE_DIR = DATA_DIR / "Structures"
GAAS_CIF = STRUCTURE_DIR / 'mp-2534_GaAs.cif'

def gaas_structure():
    """Return the AbiPy Structure for GaAs (Materials Project mp-2534)."""
    return Structure.from_file(str(GAAS_CIF))

def gs_input(ecut=6, ngkpt=(8, 8, 8)):
    """Return a GS input for GaAs on a homogeneous k-mesh."""
    structure = gaas_structure()
    pseudos = ["Ga.psp8", "As.psp8"]

    inp = abilab.AbinitInput(structure=structure, pseudos=pseudos, pseudo_dir=str(PSEUDO_DIR))
    inp.set_vars(ecut=ecut, nband=16, paral_kgb=0, iomode=3)
    inp.set_kmesh(ngkpt=ngkpt, shiftk=[0, 0, 0])
    inp.set_vars(tolvrs=1e-6)
    return inp

def setup_manager(flow, mpi_procs=4, omp_threads=1, timelimit_hour=2.0):
    manager = flow.manager.new_with_fixed_mpi_omp(mpi_procs=mpi_procs, omp_threads=omp_threads)
    manager.qadapter.set_timelimit(3600 * timelimit_hour)
    for work in flow:
        work.set_manager(manager)
    return flow

def build_kpt_conv_flow(workdir="flow_gaas_convkpt", nk_list=(1, 2, 4, 6, 8, 10)):
    """Flow with one SCF task per (automatically-generated) k-mesh density."""
    flow = flowtk.Flow(workdir=workdir)
    for nk in nk_list:
        inp = gs_input(ecut=12)
        inp.set_autokmesh(nk)
        flow.register_scf_task(inp)
    return flow

DEFAULT_WORKDIR = 'flow_gaas_convkpt'

def build_flow(options):
    flow = build_kpt_conv_flow(workdir=options.workdir or DEFAULT_WORKDIR)
    return setup_manager(flow)


@flowtk.flow_main
def main(options):
    return build_flow(options)


if __name__ == "__main__":
    sys.exit(main())
