#!/usr/bin/env python
"""
Companion to Section 6 ("Equation of state and the lattice parameter") of
the workshop notebook.

Builds the same flow as `workshop_lib.build_eos_flow()`: one SCF task per
isotropically-scaled volume of GaAs around its experimental volume. After it
completes, the notebook fits the energy-volume curve with a Birch-Murnaghan
equation of state (`abilab.EOS`) to get the equilibrium volume and bulk
modulus. As noted in the notebook, this flow deliberately uses a coarse
`ecut`/k-mesh to stay cheap -- treat the numbers as illustrative, not
converged.

Usage
-----
    python run_gaas_eos.py
    abirun.py flow_gaas_eos scheduler
    abirun.py flow_gaas_eos status

    python run_gaas_eos.py -s        # build *and* run in a single step
"""

# Auto-generated by generate_examples.py from workshop_lib.py.
# Do not edit by hand: edit workshop_lib.py and re-run generate_examples.py.

import sys
from pathlib import Path

import numpy as np
import abipy.abilab as abilab
import abipy.flowtk as flowtk
from abipy.abilab import Structure

# This script is meant to be copied -- together with the rest of this
# Tutorial/ directory -- into your own work directory. Data/Pseudos and
# Data/Structures are located relative to *this file*, wherever that ends
# up. The flow itself is built in the *current* directory: wherever you run
# "python run_gaas_eos.py" from.
SCRIPT_DIR = Path(__file__).resolve().parent
DATA_DIR = SCRIPT_DIR.parent / "Data"
PSEUDO_DIR = DATA_DIR / "Pseudos"
STRUCTURE_DIR = DATA_DIR / "Structures"
GAAS_CIF = STRUCTURE_DIR / 'mp-2534_GaAs.cif'

def gaas_structure():
    """Return the AbiPy Structure for GaAs (Materials Project mp-2534)."""
    return Structure.from_file(str(GAAS_CIF))

def setup_manager(flow, mpi_procs=4, omp_threads=1, timelimit_hour=2.0):
    manager = flow.manager.new_with_fixed_mpi_omp(mpi_procs=mpi_procs, omp_threads=omp_threads)
    manager.qadapter.set_timelimit(3600 * timelimit_hour)
    for work in flow:
        work.set_manager(manager)
    return flow

def build_eos_flow(workdir="flow_gaas_eos", scale_volumes=tuple(np.arange(0.94, 1.07, 0.02))):
    """Flow with one SCF task per isotropically-scaled volume of GaAs."""
    flow = flowtk.Flow(workdir=workdir)
    structure = gaas_structure()

    for s in scale_volumes:
        scaled = structure.copy()
        scaled.scale_lattice(structure.volume * s)
        inp = abilab.AbinitInput(structure=scaled, pseudos=["Ga.psp8", "As.psp8"],
                                  pseudo_dir=str(PSEUDO_DIR))
        inp.set_vars(ecut=12, nband=16, paral_kgb=0, iomode=3, tolvrs=1e-8)
        inp.set_kmesh(ngkpt=(4, 4, 4), shiftk=[0, 0, 0])
        flow.register_scf_task(inp)

    return flow

DEFAULT_WORKDIR = 'flow_gaas_eos'

def build_flow(options):
    flow = build_eos_flow(workdir=options.workdir or DEFAULT_WORKDIR)
    return setup_manager(flow)


@flowtk.flow_main
def main(options):
    return build_flow(options)


if __name__ == "__main__":
    sys.exit(main())
