#!/usr/bin/env python
"""
Companion to Section 7 ("Phonons from DFPT") of the workshop notebook.

Builds the same flow as `workshop_lib.build_phonon_flow()`: a ground-state
task producing the WFK file, followed by the symmetry-irreducible DFPT
atomic-perturbation tasks needed to assemble the dynamical matrix (and Born
effective charges) on a coarse q-mesh. This has more tasks than the other
example flows, so it is the best candidate for running in the background
with `nohup` (see below) rather than waiting on it in a foreground shell.

Usage
-----
    python run_gaas_phonons.py
    abirun.py flow_gaas_phonons scheduler   # repeat if interrupted
    abirun.py flow_gaas_phonons status       # check progress / list tasks

    python run_gaas_phonons.py -s                       # build *and* run
    nohup python run_gaas_phonons.py -s > log 2> err &   # ... in the background
"""

# Auto-generated by generate_examples.py from workshop_lib.py.
# Do not edit by hand: edit workshop_lib.py and re-run generate_examples.py.

import sys
from pathlib import Path

import abipy.abilab as abilab
import abipy.flowtk as flowtk
from abipy.abilab import Structure

# This script is meant to be copied -- together with the rest of this
# Tutorial/ directory -- into your own work directory. Data/Pseudos and
# Data/Structures are located relative to *this file*, wherever that ends
# up. The flow itself is built in the *current* directory: wherever you run
# "python run_gaas_phonons.py" from.
SCRIPT_DIR = Path(__file__).resolve().parent
DATA_DIR = SCRIPT_DIR.parent / "Data"
PSEUDO_DIR = DATA_DIR / "Pseudos"
STRUCTURE_DIR = DATA_DIR / "Structures"
GAAS_CIF = STRUCTURE_DIR / 'mp-2534_GaAs.cif'

def gaas_structure():
    """Return the AbiPy Structure for GaAs (Materials Project mp-2534)."""
    return Structure.from_file(str(GAAS_CIF))

def setup_manager(flow, mpi_procs=4, omp_threads=1, timelimit_hour=2.0):
    manager = flow.manager.new_with_fixed_mpi_omp(mpi_procs=mpi_procs, omp_threads=omp_threads)
    manager.qadapter.set_timelimit(3600 * timelimit_hour)
    for work in flow:
        work.set_manager(manager)
    return flow

def build_phonon_flow(workdir="flow_gaas_phonons", ecut=8, ngkpt=(4, 4, 4), ph_ngqpt=(2, 2, 2)):
    """
    PhononFlow for GaAs: one GS task producing the WFK file used by DFPT,
    followed by the (symmetry-irreducible) atomic-perturbation tasks needed
    to build the dynamical matrix on a `ph_ngqpt` q-mesh.
    """
    structure = gaas_structure()
    inp = abilab.AbinitInput(structure=structure, pseudos=["Ga.psp8", "As.psp8"],
                              pseudo_dir=str(PSEUDO_DIR))
    inp.set_vars(ecut=ecut, nband=16, paral_kgb=0, iomode=3, tolvrs=1e-8)
    inp.set_kmesh(ngkpt=ngkpt, shiftk=[0, 0, 0])

    return flowtk.PhononFlow.from_scf_input(workdir, inp, ph_ngqpt=ph_ngqpt, with_becs=True)

DEFAULT_WORKDIR = 'flow_gaas_phonons'

def build_flow(options):
    flow = build_phonon_flow(workdir=options.workdir or DEFAULT_WORKDIR)
    return setup_manager(flow)


@flowtk.flow_main
def main(options):
    return build_flow(options)


if __name__ == "__main__":
    sys.exit(main())
