#!/usr/bin/env python
"""
Companion to Section 4.1 ("ecut convergence") of the workshop notebook.

Builds the same flow as `workshop_lib.build_ecut_conv_flow()`: one SCF task
per value of `ecut`. After it completes, the notebook's `GsrRobot` /
`ConvergenceAnalyzer` cells collect the results into a convergence plot.

Usage
-----
    python run_gaas_convecut.py
    abirun.py flow_gaas_convecut scheduler
    abirun.py flow_gaas_convecut status

    python run_gaas_convecut.py -s        # build *and* run in a single step
"""

# Auto-generated by generate_examples.py from workshop_lib.py.
# Do not edit by hand: edit workshop_lib.py and re-run generate_examples.py.

from pathlib import Path

import abipy.abilab as abilab
import abipy.flowtk as flowtk
from abipy.abilab import Structure

# This script is meant to be copied -- together with the rest of this
# Tutorial/ directory -- into your own work directory. Data/Pseudos and
# Data/Structures are located relative to *this file*.
SCRIPT_DIR = Path(__file__).resolve().parent
DATA_DIR = SCRIPT_DIR.parent / "Data"
PSEUDO_DIR = DATA_DIR / "Pseudos"
STRUCTURE_DIR = DATA_DIR / "Structures"
GAAS_CIF = STRUCTURE_DIR / 'mp-2534_GaAs.cif'


def gs_input(ecut=6, ngkpt=(8, 8, 8)):
    """Return a GS input for GaAs on a homogeneous k-mesh."""
    structure = Structure.from_file(str(GAAS_CIF))
    pseudos = ["Ga.psp8", "As.psp8"]

    inp = abilab.AbinitInput(structure=structure, pseudos=pseudos, pseudo_dir=str(PSEUDO_DIR))
    inp.set_vars(ecut=ecut, nband=16, paral_kgb=0, iomode=3)
    inp.set_kmesh(ngkpt=ngkpt, shiftk=[0, 0, 0])
    inp.set_vars(tolvrs=1e-6)
    return inp


def build_ecut_conv_flow(workdir, ecut_list=range(10, 40, 5)):
    """Flow with one SCF task per value of ecut."""
    flow = flowtk.Flow(workdir=workdir)
    for ecut in ecut_list:
        flow.register_scf_task(gs_input(ecut=ecut))
    return flow


def setup_manager(flow, mpi_procs=4, omp_threads=1, timelimit_hour=2.0):
    manager = flow.manager.new_with_fixed_mpi_omp(mpi_procs=mpi_procs, omp_threads=omp_threads)
    manager.qadapter.set_timelimit(3600 * timelimit_hour)
    for work in flow:
        work.set_manager(manager)
    return flow


def build_flow(workdir=None):
    # Set working directory (default is constructed from the script name)
    if not workdir:
        workdir = Path(__file__).name.replace(".py", "").replace("run_", "flow_")

    flow = build_ecut_conv_flow(workdir=workdir)
    flow = setup_manager(flow, mpi_procs=4, omp_threads=1)
    return flow


def main():
    flow = build_flow()
    flow.build_and_pickle_dump()


if __name__ == "__main__":
    main()
