#!/usr/bin/env python
"""
Companion to Section 5 ("Band structures: GaAs vs Si") of the workshop
notebook, Si half.

Builds the same flow as `workshop_lib.build_si_ebands_flow()`: a
ground-state run on a homogeneous k-mesh followed by a non-self-consistent
run along the L-Gamma-X path, this time for silicon. See also
`run_gaas_ebands.py` for the GaAs run this is compared against -- GaAs has a
direct gap at Gamma, while silicon's fundamental gap is indirect.

Usage
-----
    python run_si_ebands.py
    abirun.py flow_si_ebands scheduler
    abirun.py flow_si_ebands status

    python run_si_ebands.py -s        # build *and* run in a single step
"""

# Auto-generated by generate_examples.py from workshop_lib.py.
# Do not edit by hand: edit workshop_lib.py and re-run generate_examples.py.

import sys
from pathlib import Path

import abipy.abilab as abilab
import abipy.flowtk as flowtk
from abipy.abilab import Structure

# This script is meant to be copied -- together with the rest of this
# Tutorial/ directory -- into your own work directory. Data/Pseudos and
# Data/Structures are located relative to *this file*, wherever that ends
# up. The flow itself is built in the *current* directory: wherever you run
# "python run_si_ebands.py" from.
SCRIPT_DIR = Path(__file__).resolve().parent
DATA_DIR = SCRIPT_DIR.parent / "Data"
PSEUDO_DIR = DATA_DIR / "Pseudos"
STRUCTURE_DIR = DATA_DIR / "Structures"
SI_CIF = STRUCTURE_DIR / 'mp-149_Si.cif'
FCC_KPATH = [[0.5, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.5, 0.5]]

def si_structure():
    """Return the AbiPy Structure for Si (Materials Project mp-149)."""
    return Structure.from_file(str(SI_CIF))

def _bandstructure_inputs(structure, pseudos, ecut, ngkpt, kptbounds,
                           nband_scf=16, nband_nscf=40):
    multi = abilab.MultiDataset(structure=structure, pseudos=pseudos,
                                 pseudo_dir=str(PSEUDO_DIR), ndtset=2)
    multi.set_vars(ecut=ecut, nband=nband_scf, nbdbuf=4, paral_kgb=0, iomode=3)

    # Dataset 1: GS run on a homogeneous k-mesh.
    multi[0].set_kmesh(ngkpt=ngkpt, shiftk=[0, 0, 0])
    multi[0].set_vars(tolvrs=1e-8)

    # Dataset 2: NSCF run along a k-path.
    multi[1].set_kpath(ndivsm=10, kptbounds=kptbounds)
    multi[1].set_vars(nband=nband_nscf, tolwfr=1e-12)

    return multi.split_datasets()

def setup_manager(flow, mpi_procs=4, omp_threads=1, timelimit_hour=2.0):
    manager = flow.manager.new_with_fixed_mpi_omp(mpi_procs=mpi_procs, omp_threads=omp_threads)
    manager.qadapter.set_timelimit(3600 * timelimit_hour)
    for work in flow:
        work.set_manager(manager)
    return flow

def build_si_ebands_flow(workdir="flow_si_ebands"):
    scf_input, nscf_input = _bandstructure_inputs(
        si_structure(), ["Si.psp8"], ecut=25, ngkpt=(4, 4, 4),
        kptbounds=FCC_KPATH)
    return flowtk.bandstructure_flow(workdir, scf_input, nscf_input)

DEFAULT_WORKDIR = 'flow_si_ebands'

def build_flow(options):
    flow = build_si_ebands_flow(workdir=options.workdir or DEFAULT_WORKDIR)
    return setup_manager(flow)


@flowtk.flow_main
def main(options):
    return build_flow(options)


if __name__ == "__main__":
    sys.exit(main())
